repos:
-   repo: local
    hooks:
    - id: black
      name: black
      language: system
      entry: python -m black
      types: [python]
    - id: pytest
      name: pytest
      language: system
      pass_filenames: false
      entry: python -m pytest -q
      types: [python]
    - id: ruff
      name: ruff
      language: system
      entry: python -m ruff
      types: [python]
      exclude: ^doc/conf.py
    - id: mypy
      name: mypy
      language: system
      entry: python -m mypy
      types: [python]
      exclude: ^doc/conf.py|^test
